# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    cmds:
      - docker run --rm -u $UID -v $(pwd):/var/build darkmattercoder/qt-build:latest build
