# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build-qt:
    cmds:
      - docker run --rm -u $UID -v $(pwd):/var/build darkmattercoder/qt-build:latest build

  build-linux:
    cmds:
      - docker run -it -v $(pwd):/workdir burningdaylight/mingw-arch:qt /bin/bash

  build-windows-builder:
    # Build the docker image that builds the windows release
    cmds:
      #- docker run --rm -it -v $(pwd):/mnt builder.dockerfile
      - docker build -t qt -f builder.dockerfile .
  build-windows-release:
    cmds:
      # Now extract the generated binary
      - docker run -it -v $(pwd):/src qt make -C build